apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app-task03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: my-nodejs-app-task03
          image: rpdharanidhar/devops-task03:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: dharani
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: dharani
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-task03
spec:
  selector:
    app: my-nodejs-app-task03
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: my-mongodb-task03
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: dharani
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: dharani
  type: ClusterIP
