---
- name: Check VM load
  hosts: all
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_pass: "mg"
  become: true
  tasks:
    - name: Ping hosts
      ping: all

    - name: Get load averages
      shell: uptime
      register: uptime_output

    - name: Display load averages
      debug:
        msg: "{{ uptime_output.stdout }}"